---
# This compose file is for a client without pulseaudio
networks:
  default:                # default network for this project


services:
  snapcast:
    # snapcast client for audio playback
    container_name: snapcast
    image: "ghcr.io/florian-asche/docker-snapcast:0.29.0-1"
    restart: unless-stopped
    network_mode: "host"
    entrypoint: /usr/bin/snapclient
    user: "1337"
    environment:
      - START_SNAPCLIENT=true
    command:
      #- "--list" # List devices
      - "--host"
      - "192.168.33.5"
      - "--hostID"
      - "dexter"
      - "--soundcard"
      - "default"
    devices:
      - /dev/snd:/dev/snd
      - /dev/bus/usb
    group_add:
      - audio
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
