---
# This compose file is for a client with pulseaudio like ubuntu desktop
# Note: The container you can use "pactl info" to debug pulseaudio
# Note: The userid 1337 is the id from my user. You need to change that and the path to the pulse cookie (home directory).
networks:
  default:                # default network for this project


services:
  snapcast:
    # snapcast client for audio playback
    container_name: snapcast
    image: "ghcr.io/florian-asche/docker-snapcast:0.29.0-1"
    restart: unless-stopped
    network_mode: "host"
    entrypoint: /usr/bin/snapclient
    user: "1337"
    environment:
      - START_SNAPCLIENT=true
      - PULSE_SERVER=unix:/tmp/pulse_native
      - PULSE_COOKIE=/tmp/pulse_cookie
    command:
      #- "--list" # List devices
      - "--host"
      - "192.168.33.5"
      - "--hostID"
      - "dexter"
      - "--soundcard"
      - "default"
    group_add:
      - audio
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # 1337 is my user id from the local user i used on my ubuntu desktop
      - /run/user/1337/pulse/native:/tmp/pulse_native
      # /home/florian is my home directory
      - /home/florian/.config/pulse/cookie:/tmp/pulse_cookie
